routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\LupaPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::controller(RegisterController::class)->name('register.')->prefix('register')->group(function () {
    Route::get('/', 'formRegister')->name('form-register');
    Route::post('/simpan-register', 'simpanRegister')->name('simpan-register');
});

Route::controller(LoginController::class)->name('login.')->prefix('login')->group(function () {
    Route::get('/', 'formLogin')->name('form-login');
    Route::post('/proses-login', 'ProsesLogin')->name('proses-login');
});

Route::controller(AdminController::class)->name('admin.')->middleware('CekLogin:admin')->prefix('admin')->group(function () {
    Route::get('/', 'BerandaAdmin')->name('beranda');
});

Route::controller(UserController::class)->name('user.')->middleware('CekLogin:user')->prefix('users')->group(function () {
    Route::get('/', 'BerandaUser')->name('beranda');
});

Route::controller(LogoutController::class)->name('logout.')->prefix('logout')->group(function () {
    Route::get('/', 'logout')->name('proses');
});

Route::controller(LupaPasswordController::class)->name('forgot.')->prefix('forgot')->group(function () {
    Route::get('/', 'formLupapassword')->name('form-forgot');
    Route::post('/proses', 'prosesLupaPassword')->name('proses');
});

app/Models/Pengguna.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticable;

class Pengguna extends Authenticable
{
    use HasFactory, Notifiable;

    protected $table = "pengguna";

    public $timestamps = true;

    protected $fillable = [
        'nama',
        'username',
        'level',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/pengguna/email_lupa_password.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
    xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
    <!--[if gte mso 9]><xml>
        <o:OfficeDocumentSettings>
        <o:AllowPNG/>
        <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
        </xml><![endif]-->
    <!-- fix outlook zooming on 120 DPI windows devices -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->
    <meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS 7-9 -->
    <meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS 7-9 -->
    <title>Lupa Password</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900" rel="stylesheet">

    <style type="text/css">
        html {
            background: #fbfbfb;
            font-family: 'Roboto', sans-serif;
        }

        body {
            margin: 0;
            padding: 0;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        table {
            border-spacing: 0;
        }

        table td {
            border-collapse: collapse;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
            line-height: 100%;
        }

        .ReadMsgBody {
            width: 100%;
            background-color: #ebebeb;
        }

        table {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        .yshortcuts a {
            border-bottom: none !important;
        }

        @media screen and (max-width: 599px) {

            .force-row,
            .container {
                width: 100% !important;
                max-width: 100% !important;
            }
        }

        @media screen and (max-width: 400px) {
            .container-padding {
                padding-left: 12px !important;
                padding-right: 12px !important;
            }
        }

        .ios-footer a {
            color: #aaaaaa !important;
            text-decoration: underline;
        }

        a[href^="x-apple-data-detectors:"],
        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

    </style>
</head>

<body style="margin:0; padding:0;" bgcolor="#F0F0F0" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

    <!-- 100% background wrapper (grey background) -->
    <table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0" bgcolor="#F0F0F0">
        <tr>
            <td align="center" valign="top" bgcolor="#F0F0F0" style="background-color: #FBFBFB;">
                <br>
                <!-- 600px container (white background) -->
                <table border="0" width="600" cellpadding="0" cellspacing="0" class="container"
                    style="width:600px;max-width:600px;box-shadow: 0 0 8px rgba(51, 51, 51, 0.5);">
                    <tr>
                        <td class="container-padding header" align="left"
                            style="font-family:Roboto, Arial, sans-serif;font-size:20px;font-weight:bold;padding-bottom:1em;color:#fff;padding-left:24px;padding-right:24px;padding-top: 1em;background-color: #2270B9">
                            <span style="float: right;">RESET PASSWORD</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="container-padding content" align="left" style="padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:12px;background-color:#ffffff;background: url('#')no-repeat;background-size: 70%;background-position: center;border-bottom: solid 1em #236fb9;">

                                <div class="body-text" style="font-family:Roboto, Arial, sans-serif;font-size:14px;line-height:20px;text-align:left;color:#333333">
                                    <br>
                                    Yth. Bpk./Ibu <strong>{{ $datas['nama_pengguna'] }}</strong>,<br>
                                    Kami menerima permintaan reset password akun Anda,
                                    <br><br>
                                </div>

                                <div class="hr" style="height:1px;border-bottom:1px solid #cccccc">&nbsp;</div>
                                <br>

                                <div  align="center" style="margin-bottom: 48px;margin-top: 30px;">
                                    <a href="{{ $datas['url_reset'] }}" style="text-decoration: none;font-size: 18px;" >
                                        <div style="padding: 15px 0px 15px 0px; background-color: #2270B9; text-align: center; color: white; width: 200px;" >
                                            Reset Password
                                        </div>
                                    </a>
                                </div>

                                {{ $datas['url_reset'] }}

                                <div class="hr" style="height:1px;border-bottom:1px solid #cccccc;clear: both;">&nbsp;</div>

                                <div class="body-text" style="font-family:Roboto, Arial, sans-serif;font-size:14px;line-height:20px;text-align:left;color:#333333">
                                    <br>
                                    Apabila Anda tidak pernah meminta reset password, segera hubungi petugas Customer Service
                                    <br><br>
                                    Terima Kasih,<br>
                                    SITAU<br><br>
                                </div>

                            </td>
                        </tr>

                    </table>
                    <!--/600px container -->
                </td>
            </tr>
        </table>
        <!--/100% background wrapper-->

    </body>
</html>

resources/views/pengguna/form_login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {{-- <link rel="stylesheet" type="text/css" href="{!! asset('asset/register.css') !!}"> --}}
  </head>
  <style>
    body {
        background-color: Beige;
    }


        .custom-card {
        border-bottom: 4px solid #2979ff;
        background-color: rgba(0, 0, 0, 0.3);
        box-shadow: 0 0 10px rgba(255, 0, 0, 0.3);
        text-transform: uppercase;
        }
        body {
            background-image: url('/gambar/geeks-2894621_1280.jpg');
        }
        .card-body h5 {
            color:white;
        }
        .card-body form label{
            color:white;
        }
        .card-body form input{
            margin-bottom: 15px;
            border: none;
            background-color: transparent;
            border-bottom: 2px solid #2979ff;
            color: white;
            font-size: 20px;
        }


        input[type="email"],
        input[type="password"] {
            background-color: transparent !important;
            color: white !important;
        }

  </style>
  <body>


          {{-- form login --}}

          <div class="container m-5">
            <div class="row">
              <div class="col-12 mx-auto">
                <div class="card custom-card">
                  <div class="card-body">
                    <h3>
                        @if($errors->any())
                        @foreach($errors->all() as $error)
                          <div class="alert alert-danger" role="alert">
                            {{ $error }}
                          </div>
                        @endforeach
                      @endif

                            @if(session('error'))
                                 <div class="alert alert-danger">
                                {{ session('error') }}
                                 </div>
                             @endif
                    </h3>
                  <h5 class="card-title text-center">Silahkan login</h5>

                  <form action="{{ route('login.proses-login') }}" method="POST">
                    {{ csrf_field() }}

                    <div class="row mb-2">
                      <div class="md-2">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                      </div>
                    </div>
                    <hr>
                    <div class="mb-2">
                      <label for="password" class="form-label">Password</label>
                      <input type="password" class="form-control" id="password" name="password" value="{{ old('password') }}" required>
                    </div>
                    <div class="mb-2">
                        <a href="{{url('forgot') }}" class="text-white">Lupa password?</a>
                      </div>
                      <hr>
                      <button type="submit" class="btn btn-primary">login</button>
                  </form>


                </div>
                </div>
              </div>
            </div>
          </div>
          {{-- form  selesai --}}

          {{-- content --}}
          {{-- content selesai --}}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/pengguna/form_lupa_password.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lupa Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
      body {
        background-color: beige;
      }

      .custom-card {
        border-bottom: 4px solid #2979ff;
        background-color: rgba(0, 0, 0, 0.3);
        box-shadow: 0 0 10px rgba(255, 0, 0, 0.3);
        text-transform: uppercase;
      }

      .card-body h5 {
        color: white;
      }

      .card-body form label {
        color: white;
      }

      .card-body form input {
        margin-bottom: 15px;
        border: none;
        background-color: transparent;
        border-bottom: 2px solid #2979ff;
        color: white;
        font-size: 20px;
      }

      input[type="email"],
      input[type="password"] {
        background-color: transparent !important;
        color: white !important;
      }
    </style>
  </head>
  <body>
    <div class="container m-5">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="card custom-card">
            <div class="card-body">
              <h3>
                @if($errors->any())
                @foreach($errors->all() as $error)
                  <div class="alert alert-danger" role="alert">
                    {{ $error }}
                  </div>
                @endforeach
                @endif

                @if(session('error'))
                <div class="alert alert-danger">
                  {{ session('error') }}
                </div>
                @endif
              </h3>
              <h5 class="card-title text-center">Lupa Password</h5>
              <form action="{{ route('forgot.proses') }}" method="POST">
                {{ csrf_field() }}
                <div class="row mb-2">
                  <div class="md-2">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                  </div>
                </div>
                <hr>
                <button type="submit" class="btn btn-primary">Kirim Tautan Reset Password</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/pengguna/form_register.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{!! asset('asset/register.css') !!}">
  </head>
  <body>
        <div class="container m-5">
            <div class="row mb-xl-2 justify-content-center">
              <div class="card custom-card mb-xl-4">
                <div class="card-body mb-xl-2">
                    <h3>
                        @if (session('error'))
                            {{ session('error') }}
                            @endif
                            @if(session('sucses'))
                            {{ session('sucses') }}
                            @endif
                    </h3>
                  <h5 class="card-title text-center">Create account</h5>
                  <hr>
                  <form action="{{ route('register.simpan-register') }}" method="POST">
                    @csrf
                    <div class="row mb-2">
                      <div class="col-md-6">
                        <label for="nama" class="form-label">Nama</label>
                        <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama') }}" required>
                      </div>
                      <div class="col-md-6">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{ old('username') }}">
                      </div>
                    </div>
                    <hr>
                    <div class="row mb-2">
                      <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                      </div>
                      <div class="col-md-6">
                        <label for="level" class="form-label">Level</label>
                        <select class="form-select" id="level" name="level" value="{{ old('level') }}" required>
                          <option value="admin">Admin</option>
                          <option value="user">User</option>
                        </select>
                      </div>
                    </div>
                    <hr>
                    <div class="mb-2">
                      <label for="password" class="form-label">Password</label>
                      <input type="password" class="form-control" id="password" name="password" value="{{ old('password') }}" autocomplete="of" required>
                    </div>
                    <hr>
                    <div class="row">
                        <button type="submit" class="btn btn-primary">Daftar</button>
                    <span class="text-muted text-center">Sudah punya akun?
                        <br>
                        <a href="{{ route('login.form-login') }}" class="text-dark"> clik login</a>

                    </span>

                    </div>

                  </form>
                </div>
              </div>
            </div>
          </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>